CREATE TABLE `__TABLE_NAME__` (
  `wr_id` int(11) NOT NULL AUTO_INCREMENT,
  `wr_num` int(11) NOT NULL DEFAULT '0',
  `wr_reply` varchar(10) NOT NULL,
  `wr_parent` int(11) NOT NULL DEFAULT '0',
  `wr_is_comment` tinyint(4) NOT NULL DEFAULT '0',
  `wr_write_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `wr_name` varchar(12) NOT NULL,
  `wr_address` varchar(255) NOT NULL,
  `wr_district` varchar(255) NOT NULL,
  `wr_floor` int(11) NOT NULL DEFAULT '0',
  `wr_area_p` int(11) NOT NULL DEFAULT '0',
  `wr_area_m` float(20) NOT NULL DEFAULT '0',
  `wr_sale_price` int(11) NOT NULL DEFAULT '0',
  `wr_p_sale_price` int(11) NOT NULL DEFAULT '0',
  `wr_loan` int(11) NOT NULL DEFAULT '0',
  `wr_sale_deposit` int(11) NOT NULL DEFAULT '0',
  `wr_rent_deposit` int(11) NOT NULL DEFAULT '0',
  `wr_profit_rate` int(11) NOT NULL DEFAULT '0',
  `wr_m_rate` int(11) NOT NULL DEFAULT '0',
  `wr_mt_cost` int(11) NOT NULL DEFAULT '0',
  `wr_premium_o` int(11) NOT NULL DEFAULT '0',
  `wr_premium_b` int(11) NOT NULL DEFAULT '0',
  `wr_renter_contact` varchar(255) NOT NULL,
  `wr_lessor_contact` varchar(255) NOT NULL,
  `wr_parcel_contact` varchar(255) NOT NULL,
  `wr_room_type` varchar(255) NOT NULL,
  `wr_room_count` tinyint(4) NOT NULL DEFAULT '0',
  `wr_rest_count` tinyint(4) NOT NULL DEFAULT '0',
  `wr_o_air_cond` varchar(1) NOT NULL,
  `wr_o_fridger` varchar(1) NOT NULL,
  `wr_0_washer` varchar(1) NOT NULL,
  `wr_o_tv` varchar(1) NOT NULL,
  `wr_o_internet` varchar(1) NOT NULL,
  `wr_o_microwave` varchar(1) NOT NULL,
  `wr_o_desk` varchar(1) NOT NULL,
  `wr_o_bookshelf` varchar(1) NOT NULL,
  `wr_o_bed` varchar(1) NOT NULL,
  `wr_o_closet` varchar(1) NOT NULL,
  `wr_o_shoe_rack` varchar(1) NOT NULL,
  `wr_o_sink` varchar(1) NOT NULL,
  `wr_o_heating` varchar(1) NOT NULL,
  `wr_o_subway` varchar(1) NOT NULL,
  `wr_o_parking` varchar(1) NOT NULL,
  `wr_o_elevator` varchar(1) NOT NULL,
  `wr_direction` varchar(3) NOT NULL,
  `wr_move_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `wr_vacant` varchar(1) NOT NULL,
  PRIMARY KEY (`wr_id`),
  KEY `wr_num_reply_parent` (`wr_num`,`wr_reply`,`wr_parent`),
  KEY `wr_is_comment` (`wr_is_comment`,`wr_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;
